name: Build and test

on: push

jobs:
  test:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install go 1.21
      - name: Setup go
        uses: actions/setup-go@v4
        with: # Specify input variables to the action
          go-version: "1.21.x"

      # Shell script to print the version
      - run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
